FROM --platform=linux/amd64 node:20-alpine
WORKDIR /app

# 개발 환경 설정
ENV NODE_ENV=development

# package.json과 package-lock.json 복사
COPY package*.json ./

# 의존성 설치
RUN npm install

# 환경 변수 파일 복사
COPY .env .env

# 소스 코드 복사
COPY . .

# 개발 서버 포트 노출
EXPOSE 3000

# 개발 서버 실행 (자동 리로드 활성화)
CMD ["npm", "run", "start:dev"] 