name: Deploy to Synology Server

on:
  push:
    branches:
      - main # main 브랜치에 푸시할 때마다 배포

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass & rsync
        run: sudo apt-get install -y sshpass rsync

      - name: Set up SSH config
        run: |
          mkdir -p ~/.ssh
          echo -e "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SYNOLOGY_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to Synology (using sshpass)
        env:
          SYNOLOGY_HOST: ${{ secrets.SYNOLOGY_HOST }}
        run: |
          # SSH 접속 및 Docker Compose 실행
          sshpass -p ${{ secrets.SYNOLOGY_PASSWORD }} ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SYNOLOGY_USERNAME }}@${{ secrets.SYNOLOGY_HOST }} 'bash -s' << 'EOF'
            # 1. Docker와 Docker Compose 설치 여부 확인 및 설치
            if ! command -v docker &> /dev/null
            then
              echo "Docker could not be found, installing..."
              echo ${{ secrets.SYNOLOGY_PASSWORD }} | sudo -S apt-get update
              echo ${{ secrets.SYNOLOGY_PASSWORD }} | sudo -S apt-get install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://get.docker.com -o get-docker.sh
              echo ${{ secrets.SYNOLOGY_PASSWORD }} | sudo -S sh get-docker.sh
            fi

            if ! command -v docker-compose &> /dev/null
            then
              echo "Docker Compose could not be found, installing..."
              echo ${{ secrets.SYNOLOGY_PASSWORD }} | sudo -S curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              echo ${{ secrets.SYNOLOGY_PASSWORD }} | sudo -S chmod +x /usr/local/bin/docker-compose
            fi

            # 2. 작업 디렉토리 생성 및 이동
            mkdir -p ${{ secrets.DEPLOY_PATH }}
            cd ${{ secrets.DEPLOY_PATH }}

            # 3. git clone 또는 pull
            if [ -d "my-react-nest-app" ]; then
              cd my-react-nest-app
              git pull origin main
            else
              git clone https://github.com/raincoat98/my-react-nest-app.git
              cd my-react-nest-app
            fi

            # 4. Docker Compose 실행
            if [ -f "docker-compose.yml" ]; then
              echo ${{ secrets.SYNOLOGY_PASSWORD }} | sudo -S /usr/local/bin/docker-compose down
              echo ${{ secrets.SYNOLOGY_PASSWORD }} | sudo -S /usr/local/bin/docker-compose up --build -d
            else
              echo "Error: docker-compose.yml not found"
              exit 1
            fi
          EOF
