name: CI/CD for React & NestJS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-timeout=30s
          --health-retries=3
          --health-start-period=5s

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # 4. Build Backend Docker image
      - name: Build Backend Docker image
        run: |
          docker-compose -f docker-compose.yml build backend

      # 5. Build Frontend Docker image
      - name: Build Frontend Docker image
        run: |
          docker-compose -f docker-compose.yml build frontend

      # 6. Run Tests (Backend)
      - name: Run Backend Tests
        run: |
          docker-compose -f docker-compose.yml up -d backend
          docker-compose -f docker-compose.yml exec backend npm run test

      # 7. Run Tests (Frontend)
      - name: Run Frontend Tests
        run: |
          docker-compose -f docker-compose.yml up -d frontend
          docker-compose -f docker-compose.yml exec frontend npm run test

      # 8. Deploy to Synology (using rsync)
      - name: Deploy to Synology (using rsync)
        env:
          SYNOLOGY_HOST: ${{ secrets.SYNOLOGY_HOST }}
          SYNOLOGY_USERNAME: ${{ secrets.SYNOLOGY_USERNAME }}
          SYNOLOGY_PASSWORD: ${{ secrets.SYNOLOGY_PASSWORD }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          # Install necessary tools
          sudo apt-get install -y sshpass rsync

          # Add the host to known hosts to prevent SSH prompts
          mkdir -p ~/.ssh
          ssh-keyscan -p $SSH_PORT $SYNOLOGY_HOST >> ~/.ssh/known_hosts

          echo "Connecting to Synology server..."

          # Use rsync to deploy the files
          rsync -avz -e "sshpass -p $SYNOLOGY_PASSWORD ssh -p $SSH_PORT" dist/ $SYNOLOGY_USERNAME@$SYNOLOGY_HOST:$DEPLOY_PATH

      # 9. Shutdown Docker Compose environment
      - name: Shut down Docker Compose
        run: |
          docker-compose -f docker-compose.yml down
