name: Deploy to Synology Server

on:
  push:
    branches:
      - main # main 브랜치에 푸시할 때마다 배포

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass & rsync
        run: sudo apt-get install -y sshpass rsync

      - name: Set up SSH config
        run: |
          mkdir -p ~/.ssh
          echo -e "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SYNOLOGY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Synology (using sshpass)
        env:
          SYNOLOGY_HOST: ${{ secrets.SYNOLOGY_HOST }}
        shell: /usr/bin/bash -e {0}
        run: |
          # SSH 접속 및 Docker Compose 실행
          sshpass -p ${{ secrets.SYNOLOGY_PASSWORD }} ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SYNOLOGY_USERNAME }}@${{ secrets.SYNOLOGY_HOST }} 'bash -s' << 'EOF'

            # 1. Docker Compose 설치 (이미 설치되어 있다면 스킵)
            if ! [ -x "$(command -v docker compose)" ]; then
              echo "Installing Docker Compose..."
              sudo -S curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo -S chmod +x /usr/local/bin/docker-compose
            else
              echo "Docker Compose is already installed."
            fi

            # 2. 작업 디렉토리로 이동
            cd /volume1/web/

            # 3. git clone 또는 pull
            if [ -d "my-react-nest-app" ]; then
              cd my-react-nest-app
              git pull origin main
            else
              git clone https://github.com/raincoat98/my-react-nest-app.git
              cd my-react-nest-app
            fi

            # 4. Docker Compose 실행
            if [ -f "docker-compose.yml" ]; then
              echo "${{ secrets.SYNOLOGY_PASSWORD }}" | sudo -S docker-compose down || true
              echo "${{ secrets.SYNOLOGY_PASSWORD }}" | sudo -S docker-compose up --build -d
            else
              echo "Error: docker-compose.yml not found"
              exit 1
            fi

          EOF
