name: Deploy to Synology Server

on:
  push:
    branches:
      - main # main 브랜치에 푸시할 때마다 배포

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass & rsync
        run: sudo apt-get install -y sshpass rsync

      - name: Set up SSH config
        env:
          SYNOLOGY_HOST: ${{ secrets.SYNOLOGY_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # SSH 포트를 설정합니다
          SSH_PORT=${{ secrets.SSH_PORT }}
          if [ -z "$SSH_PORT" ]; then
            SSH_PORT=22  # SSH_PORT가 없으면 기본 포트 22를 사용
          fi

          # SSH 키를 확인하고 known_hosts에 추가합니다.
          ssh-keyscan -p $SSH_PORT $SYNOLOGY_HOST >> ~/.ssh/known_hosts

          # 호스트 키를 확인하지 않도록 설정
          echo "Host $SYNOLOGY_HOST" >> ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy to Synology (using sshpass)
        env:
          SYNOLOGY_HOST: ${{ secrets.SYNOLOGY_HOST }}
        run: |
          # SSH 접속 및 Docker Compose 실행
          sshpass -p ${{ secrets.SYNOLOGY_PASSWORD }} ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SYNOLOGY_USERNAME }}@${{ secrets.SYNOLOGY_HOST }} 'bash -s' << 'EOF'

            # 4. 작업 디렉토리로 이동
            cd /volume1/web/

            # 5. git clone 또는 pull
            if [ -d "my-react-nest-app" ]; then
              cd my-react-nest-app
              git pull origin main
            else
              git clone https://github.com/raincoat98/my-react-nest-app.git
              cd my-react-nest-app
            fi

            # docker-compose 설치
            curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

            # 6. Docker Compose 실행
            if [ -f "docker-compose.yml" ]; then
              docker-compose down || true
              docker-compose up --build -d
            else
              echo "Error: docker-compose.yml not found"
              exit 1
            fi

          EOF
