name: CI/CD for React & NestJS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Docker Compose (if not pre-installed)
      - name: Install Docker Compose
        run: |
          if ! command -v docker-compose &> /dev/null; then
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose &&
            sudo chmod +x /usr/local/bin/docker-compose;
          fi

      # Clean Up Docker Environment Before Build (Optional)
      - name: Clean Up Docker Environment Before Build
        run: |
          docker-compose down || true &&
          docker system prune --volumes --all --force || true &&
          docker network prune --force || true

      # Build and Start Services with Docker Compose (Dynamic Ports)
      - name: Build and Start Services with Docker Compose (Dynamic Ports)
        run: |
          sed -i 's/5436:/0:/g' docker-compose.yml &&
          docker-compose up --build -d

      # Shut Down Services After Tests (Cleanup)
      - name: Shut Down Services After Tests (Cleanup)
        run: |
          docker-compose down || true &&
          docker system prune --volumes --all --force || true &&
          echo "Docker environment cleaned up."
