name: Deploy to Synology Server

on:
  push:
    branches:
      - main # main 브랜치에 푸시할 때마다 배포

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy SSH config
        run: |
          mkdir -p ~/.ssh
          echo -e "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Clone repository and deploy to Synology
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SYNOLOGY_USERNAME }}@${{ secrets.SYNOLOGY_HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_PATH }} || cd $(dirname ${{ secrets.DEPLOY_PATH }})  # 기존 폴더로 이동 (없으면 상위 폴더로 이동)
            git pull origin main || git clone https://github.com/raincoat98/my-react-nest-app.git
            cd my-react-nest-app
            sudo docker-compose down
            sudo docker-compose up --build -d  # Docker Compose로 백그라운드에서 실행
          EOF
